# Generated by Django 4.2.6 on 2023-10-30 15:56

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images1', models.ImageField(blank=True, null=True, upload_to=shop.models.get_file_path)),
                ('images2', models.ImageField(blank=True, null=True, upload_to=shop.models.get_file_path)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=hidden')),
            ],
        ),
    ]
