# Generated by Django 4.2.6 on 2023-11-01 04:39

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_images1_banner_images_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.get_file_path),
        ),
    ]
